(function(root){
 'use strict';let prepared=false,restore=null;
 const $=id=>document.getElementById(id);
 function accordion(title,id){const box=document.createElement('div');box.className='seccion-acordeon';const head=document.createElement('button');head.type='button';head.className='header-acordeon';head.textContent=title;head.setAttribute('aria-expanded','false');const content=document.createElement('div');content.id=id;content.className='contenido-acordeon';content.hidden=true;head.onclick=()=>{content.hidden=!content.hidden;head.setAttribute('aria-expanded',String(!content.hidden));};box.append(head,content);return {box,content,head};}
 function move(id,dest){const el=$(id);if(el)dest.append(el.parentElement);}
 function modalityImage(id,slot,into){const label=document.createElement('label');label.textContent='Imagen de la modalidad';const input=document.createElement('input');input.id=id;input.type='hidden';label.append(input);into.append(label);root.PricMedia.attach(input,{kind:'modality',slot,resolve:()=>root.PricClubMedia.target()});}
 function reorg(){
  if(prepared)return;const advanced=$('config-etapa4-card'),scroller=document.querySelector('#panel-config-club .scroll-interno'),info=$('ac-config-info')||$('ac-config-informacion');if(!advanced||!scroller||!info)return;prepared=true;
  const information=accordion('Información','pric-config-info'),padel=accordion('Pádel','pric-config-padel'),tennis=accordion('Tenis','pric-config-tenis'),routine=accordion('Horarios','pric-config-rutina'),policies=accordion('Políticas','pric-config-politicas');
  const foto=$('input-foto-club'),contact=document.querySelector('.config-info-campos');if(contact)information.content.append(contact);
  const name=document.createElement('label');name.textContent='Nombre del club';const nameInput=document.createElement('input');nameInput.id='input-nombre-club';nameInput.className='input-form';nameInput.readOnly=true;name.append(nameInput);information.content.prepend(name);
  if(foto){const label=foto.parentElement.querySelector('label');if(label)label.textContent='Imagen principal del club';root.PricMedia.attach(foto,{kind:'club',resolve:()=>root.PricClubMedia.target()});}
  const mp=$('config-mercadopago-card');if(mp)policies.content.append(mp);
  // Preserve all existing operating fields and their identifiers.
  while(info.firstChild)routine.content.append(info.firstChild);
  const intervals=document.createElement('div');intervals.className='pric-config-row';document.querySelectorAll('.config-horario-dia').forEach(el=>{intervals.append(el.parentElement);el.addEventListener('input',()=>{const cb=$('dia-'+el.dataset.dia);if(cb)cb.checked=!!el.value.trim();});});routine.content.append(intervals);
  ['input-anticipacion-max','input-cierres-club'].forEach(id=>move(id,routine.content));
  for(const [old,title,slot,deposit]of [['ac-config-indoor','Indoor','padel_indoor','input-sena-padel-indoor'],['ac-config-outdoor','Outdoor','padel_outdoor','input-sena-padel-outdoor']]){const content=$(old);if(!content)continue;const detail=document.createElement('details');detail.className='pric-config-inner';const summary=document.createElement('summary');summary.textContent=title;detail.append(summary,content);content.style.display='block';padel.content.append(detail);move(deposit,content);modalityImage('pric-photo-'+slot,slot,content);}
  const tennisLegacy=$('ac-config-tenis');if(tennisLegacy){tennisLegacy.hidden=true;tennisLegacy.style.display='none';tennis.content.append(tennisLegacy);}
  for(const [slot,title,count,deposit]of [['tenis_indoor','Indoor','input-canchas-tenis-indoor','input-sena-tenis-indoor'],['tenis_outdoor','Outdoor','input-canchas-tenis-outdoor','input-sena-tenis-outdoor']]){const detail=document.createElement('details');detail.className='pric-config-inner';const summary=document.createElement('summary');summary.textContent=title;const inner=document.createElement('div');detail.append(summary,inner);move(count,inner);root.PricConfigControls.tennis(slot,inner);move(deposit,inner);modalityImage('pric-photo-'+slot,slot,inner);tennis.content.append(detail);}
  // Legacy aliases still feed old calculations, but have no duplicate visible control.
  for(const id of ['input-sena-in','input-sena-out','input-sena-tenis','input-canchas-tenis']){const el=$(id);if(el){const parent=el.parentElement;el.type='hidden';parent.querySelectorAll('label').forEach(x=>x.remove());}}
  ['input-politica-cancelacion','input-politica-devolucion'].forEach(id=>move(id,policies.content));
  scroller.replaceChildren(information.box,padel.box,tennis.box,routine.box,policies.box);
  // Keep the old builder's marker so subsequent renders do not recreate duplicate controls.
  advanced.replaceChildren();advanced.className='';advanced.hidden=true;advanced.style.display='none';scroller.append(advanced);
  for(const id of ['input-sena-in','input-sena-out','input-sena-tenis','input-canchas-tenis']){const el=$(id);if(el){el.type='hidden';el.parentElement.querySelectorAll('label').forEach(x=>x.remove());}}
  information.content.hidden=false;information.head.setAttribute('aria-expanded','true');
  // Prevent a legacy configuration write from overwriting an image just uploaded.
  for(const id of ['input-primer-turno','input-ultimo-turno']){const el=$(id);if(el)el.parentElement.style.display='none';}document.querySelectorAll('.checkbox-dias').forEach(el=>el.style.display='none');
  const panel=$('panel-config-club'),save=panel.querySelector('[data-action="window.guardarConfiguracion()"]');let header=panel.querySelector('.panel-header-club');if(!header){header=document.createElement('div');header.className='panel-header-club';header.innerHTML='<h2>Configuración</h2>';panel.prepend(header);}if(save){save.textContent='Guardar';save.classList.add('pric-config-save');header.append(save);}
  root.PricConfigControls.prepare();for(const id of ['input-primer-turno','input-ultimo-turno','input-sena-in','input-sena-out','input-sena-tenis','input-canchas-tenis']){const el=$(id);if(el)el.remove();}document.querySelectorAll('.checkbox-dias').forEach(el=>el.remove());tennisLegacy?.remove();root.PricClubMedia.refresh();
 }
 function onboarding(){reorg();if($('pric-onboarding'))return;const panel=$('panel-config-club');if(!panel)return;const parent=panel.parentNode,next=panel.nextSibling;restore=()=>{if(next&&next.parentNode===parent)parent.insertBefore(panel,next);else parent.append(panel);panel.style.display='';$('pric-onboarding')?.remove();restore=null;};const overlay=document.createElement('div');overlay.id='pric-onboarding';const content=document.createElement('div');const title=document.createElement('h2');title.textContent='Configuración inicial del club';const text=document.createElement('p');text.textContent='Completá estos datos una sola vez. Al finalizar, el panel quedará bloqueado hasta la habilitación de PRIC.';const exit=document.createElement('button');exit.type='button';exit.className='pric-media-button';exit.textContent='Cerrar sesión';exit.onclick=()=>root.logoutClub();content.append(title,text,panel,exit);overlay.append(content);document.body.append(overlay);panel.style.display='block';panel.style.visibility='visible';panel.style.pointerEvents='auto';panel.removeAttribute('aria-hidden');}
 new MutationObserver(()=>{document.querySelectorAll('.pric-tournament-image:not([data-media-attached])').forEach(input=>{if(root.PricClubMedia)root.PricMedia.attach(input,{kind:'tournament',resolve:()=>{const t=root.PricClubMedia.tournament(input.dataset.id);return {id:t.id,clubId:t.clubId};}});});}).observe(document.documentElement,{childList:true,subtree:true});
 root.PricClubLayout={reorganize:reorg,onboarding,closeOnboarding:()=>restore?.()};
 const drafts=new Map();let draftClub=null;function club(){return root.CLUB_DOC_ID_ACTUAL;}function ensureClub(){if(draftClub!==club()){drafts.clear();draftClub=club();}}function key(el){return el.id||('day-'+el.dataset.dia);}function state(el){return {value:el.value,checked:el.checked};}
 document.addEventListener('input',e=>{const el=e.target;if(el.closest?.('#panel-config-club')&&el.matches('input:not([type=hidden]):not([type=file]),textarea,select,.config-horario-dia,#input-cierres-club')&&!el.readOnly){ensureClub();drafts.set(key(el),{...state(el),el});}});
 root.PricConfigDraft={restore(){ensureClub();for(const item of drafts.values()){if(item.el.isConnected){item.el.value=item.value;item.el.checked=item.checked;}}},snapshot(){ensureClub();return new Map(drafts);},acknowledge(snapshot){for(const [k,v]of snapshot)if(drafts.get(k)===v)drafts.delete(k);}};
 document.addEventListener('DOMContentLoaded',()=>{const sidebar=$('sidebar-admin-club'),nav=sidebar?.querySelector('.sidebar-menu-club'),exit=sidebar?.querySelector('.sidebar-logout-club');if(!exit||!nav)return;const mq=matchMedia('(max-width:767px)');const arrange=()=>{exit.classList.toggle('pric-fixed-mobile-exit',mq.matches);if(mq.matches)nav.append(exit);else sidebar.append(exit);};mq.addEventListener('change',arrange);arrange();});
})(window);
