(function(root){
 'use strict';
 const limits={profile:[384,80000],club:[1280,300000],modality:[960,220000],tournament:[1280,300000],sponsor:[512,120000],institutional:[1600,400000]};
 let context={};
 function configure(options){context={...context,...options};}
 async function headers(){const user=await context.user?.();if(!user)throw Error('Iniciá sesión para cargar imágenes.');const appCheck=await context.appCheck?.();if(!appCheck)throw Error('No se pudo verificar la aplicación. Volvé a intentarlo.');return {'Authorization':'Bearer '+await user.getIdToken(),'X-Firebase-AppCheck':appCheck};}
 async function optimize(file,kind){
  if(!limits[kind])throw Error('Tipo de imagen inválido.');
  if(file.size>10000000||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Elegí una imagen JPEG, PNG o WebP de hasta 10 MB.');
  const bytes=new Uint8Array(await file.arrayBuffer());const text=new TextDecoder('latin1').decode(bytes);
  if(text.includes('acTL')||text.includes('ANIM'))throw Error('No se permiten imágenes animadas.');
  const blobUrl=URL.createObjectURL(file),image=new Image();try{image.src=blobUrl;await image.decode();if(image.naturalWidth*image.naturalHeight>40000000)throw Error('La imagen tiene demasiados píxeles. Reducí su tamaño.');return await crop(image,kind);}finally{URL.revokeObjectURL(blobUrl);}
 }
 function crop(image,kind){return new Promise(resolve=>{
 const dialog=document.createElement('dialog');dialog.className='pric-media-dialog';dialog.innerHTML='<h3>Ajustar imagen</h3><p>Arrastrá el recuadro o sus esquinas para elegir el encuadre.</p><canvas tabindex="0" aria-label="Recorte: arrastrar para mover; flechas para ajustar; más y menos para cambiar tamaño"></canvas><p role="status" aria-live="polite"></p><div class="pric-media-actions"><button type="button" data-accept>Usar imagen</button><button type="button" data-cancel>Cancelar</button></div>';document.body.append(dialog);
 const canvas=dialog.querySelector('canvas'),status=dialog.querySelector('[role=status]'),ctx=canvas.getContext('2d'),scale=Math.min(480/image.naturalWidth,360/image.naturalHeight,1);canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);
 let box={x:0,y:0,w:canvas.width,h:canvas.height},drag=null,finished=false;if(kind==='profile'){box.w=box.h=Math.min(canvas.width,canvas.height);box.x=(canvas.width-box.w)/2;box.y=(canvas.height-box.h)/2;}
 function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);ctx.fillStyle='rgba(7,21,43,.5)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.beginPath();ctx.rect(box.x,box.y,box.w,box.h);ctx.clip();ctx.drawImage(image,0,0,canvas.width,canvas.height);ctx.restore();ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.strokeRect(box.x,box.y,box.w,box.h);ctx.beginPath();for(let i=1;i<3;i++){ctx.moveTo(box.x+box.w*i/3,box.y);ctx.lineTo(box.x+box.w*i/3,box.y+box.h);ctx.moveTo(box.x,box.y+box.h*i/3);ctx.lineTo(box.x+box.w,box.y+box.h*i/3);}ctx.stroke();ctx.lineWidth=5;ctx.beginPath();for(const x of [box.x,box.x+box.w])for(const y of [box.y,box.y+box.h]){ctx.moveTo(x,y+(y===box.y?18:-18));ctx.lineTo(x,y);ctx.lineTo(x+(x===box.x?18:-18),y);}for(const y of [box.y,box.y+box.h]){ctx.moveTo(box.x+box.w/2-10,y);ctx.lineTo(box.x+box.w/2+10,y);}for(const x of [box.x,box.x+box.w]){ctx.moveTo(x,box.y+box.h/2-10);ctx.lineTo(x,box.y+box.h/2+10);}ctx.stroke();}
 const point=e=>{const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};};
 canvas.onpointerdown=e=>{const p=point(e);let corner=null;for(const [name,x,y]of [['nw',box.x,box.y],['ne',box.x+box.w,box.y],['sw',box.x,box.y+box.h],['se',box.x+box.w,box.y+box.h]])if(Math.hypot(p.x-x,p.y-y)<24)corner=name;drag={p,box:{...box},corner};canvas.setPointerCapture(e.pointerId);e.preventDefault();};
 canvas.onpointermove=e=>{if(!drag)return;const p=point(e),b=drag.box,dx=p.x-drag.p.x,dy=p.y-drag.p.y;if(!drag.corner){box.x=Math.max(0,Math.min(canvas.width-box.w,b.x+dx));box.y=Math.max(0,Math.min(canvas.height-box.h,b.y+dy));}else{let left=b.x,right=b.x+b.w,top=b.y,bottom=b.y+b.h;if(drag.corner.includes('w'))left=Math.max(0,Math.min(right-32,b.x+dx));else right=Math.min(canvas.width,Math.max(left+32,b.x+b.w+dx));if(drag.corner.includes('n'))top=Math.max(0,Math.min(bottom-32,b.y+dy));else bottom=Math.min(canvas.height,Math.max(top+32,b.y+b.h+dy));if(kind==='profile'){const size=Math.min(right-left,bottom-top);if(drag.corner.includes('w'))left=right-size;else right=left+size;if(drag.corner.includes('n'))top=bottom-size;else bottom=top+size;}box={x:left,y:top,w:right-left,h:bottom-top};}draw();};canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;};
 canvas.onkeydown=e=>{const d={ArrowLeft:[-2,0],ArrowRight:[2,0],ArrowUp:[0,-2],ArrowDown:[0,2]}[e.key];if(d){box.x=Math.max(0,Math.min(canvas.width-box.w,box.x+d[0]));box.y=Math.max(0,Math.min(canvas.height-box.h,box.y+d[1]));}else if(['+','-','='].includes(e.key)){const factor=e.key==='-'?1.05:.95;box.w=Math.max(Math.min(32,canvas.width),Math.min(canvas.width-box.x,box.w*factor));box.h=Math.max(Math.min(32,canvas.height),Math.min(canvas.height-box.y,box.h*factor));if(kind==='profile')box.w=box.h=Math.min(box.w,box.h);}else return;e.preventDefault();draw();};
 function finish(result){if(finished)return;finished=true;dialog.close();dialog.remove();resolve(result);}dialog.oncancel=e=>{e.preventDefault();finish(null);};dialog.querySelector('[data-cancel]').onclick=()=>finish(null);
 dialog.querySelector('[data-accept]').onclick=async()=>{const button=dialog.querySelector('[data-accept]');button.disabled=true;status.textContent='Optimizando…';try{const [edge,max]=limits[kind],output=document.createElement('canvas');for(const reduction of [1,.85,.7]){const ratio=Math.min(1,edge*reduction/Math.max(box.w/scale,box.h/scale));output.width=Math.max(1,Math.round(box.w/scale*ratio));output.height=Math.max(1,Math.round(box.h/scale*ratio));output.getContext('2d').drawImage(image,box.x/scale,box.y/scale,box.w/scale,box.h/scale,0,0,output.width,output.height);for(const quality of [.78,.65,.5]){const blob=await new Promise(r=>output.toBlob(r,'image/webp',quality));if(blob&&blob.type==='image/webp'&&blob.size<=max){finish(blob);return;}}}throw Error('No se pudo reducir el peso. Probá con otra imagen.');}catch(e){status.textContent=e.message;button.disabled=false;}};draw();dialog.showModal();
 });}
 async function upload(target,blob){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),60000);try{const response=await fetch((context.api||'https://us-central1-pric-60f50.cloudfunctions.net/api')+'/media/upload?'+new URLSearchParams(target),{method:'POST',headers:{...await headers(),'Content-Type':'image/webp'},body:blob,signal:controller.signal});const data=await response.json();if(!response.ok||!data.ok)throw Error(data.error||'No se pudo subir la imagen.');return data;}finally{clearTimeout(timeout);}}
 function attach(input,target){
  if(!input||input.dataset.mediaAttached)return;input.dataset.mediaAttached='true';input.type='hidden';
  const area=document.createElement('div');area.className='pric-media-field';const preview=document.createElement('img');preview.alt='Imagen actual';preview.loading='lazy';preview.hidden=!input.value;if(input.value)preview.src=input.value;if(target.kind==='profile')preview.className='pric-media-avatar';
  const pick=document.createElement('input');pick.type='file';pick.accept='image/jpeg,image/png,image/webp';pick.hidden=true;
  const button=document.createElement('button');button.type='button';button.className='pric-media-button';button.textContent=input.value?'Reemplazar imagen':'Elegir imagen';
  const status=document.createElement('span');status.className='pric-media-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');
  const clear=document.createElement('button');clear.type='button';clear.className='pric-media-button';clear.textContent='Quitar';clear.hidden=!input.value;
  area.append(preview,button,clear,pick,status);input.after(area);let busy=false;
  function refresh(){preview.hidden=!input.value;if(input.value)preview.src=input.value;else preview.removeAttribute('src');clear.hidden=!input.value;button.textContent=input.value?'Reemplazar imagen':'Elegir imagen';}
  input.addEventListener('change',refresh);button.onclick=()=>{if(!busy)pick.click();};
  pick.onchange=async()=>{if(!pick.files[0]||busy)return;busy=true;button.disabled=true;clear.disabled=true;try{status.textContent='Preparando…';const resolved={...target,...(typeof target.resolve==='function'?target.resolve():{})};delete resolved.resolve;const image=await optimize(pick.files[0],resolved.kind);if(!image){status.textContent='';return;}status.textContent='Subiendo…';const result=await upload(resolved,image);input.value=result.url;input.dispatchEvent(new Event('change',{bubbles:true}));await context.onUploaded?.(resolved,result);status.textContent='Imagen guardada · '+Math.round(result.bytes/1000)+' KB';}catch(e){status.textContent=e.name==='AbortError'?'La carga tardó demasiado. Podés reintentarlo.':e.message;}finally{busy=false;button.disabled=false;clear.disabled=false;pick.value='';refresh();}};
  clear.onclick=async()=>{if(busy)return;busy=true;clear.disabled=true;button.disabled=true;try{const resolved={...target,...(typeof target.resolve==='function'?target.resolve():{})};delete resolved.resolve;const response=await fetch((context.api||'https://us-central1-pric-60f50.cloudfunctions.net/api')+'/media/remove',{method:'POST',headers:{...await headers(),'Content-Type':'application/json'},body:JSON.stringify(resolved)});const result=await response.json();if(!response.ok||!result.ok)throw Error(result.error||'No se pudo quitar la imagen.');input.value='';input.dispatchEvent(new Event('change',{bubbles:true}));await context.onUploaded?.(resolved,{url:'',bytes:0});status.textContent='Imagen retirada.';}catch(e){status.textContent=e.message;}finally{busy=false;clear.disabled=false;button.disabled=false;refresh();}};
 }
 root.PricMedia={configure,attach,optimize,upload};
})(window);
